export default {
  'TXT_APP_STARTING': 'Starting App',
  'TXT_APP_RUNNING': 'Running in',
  'TXT_APP_ENVIRONMENT': 'environment',
  'TXT_EXPRESS_UP': 'Express framework is loaded',
  'TXT_APP_START_AT': 'App started at',
  'TXT_HOST_ACCESS': 'Http Access',
  'TXT_HOST_STATE': 'Http Server State',
  'TXT_HTTP_SERVER_UP': '-> Http server is running',
  'TXT_HOST_DOWN': 'Stopped',
  'TXT_SOCKETIO_UP': '-> Socketio listening event',
  'TXT_DB_STATE': '-> SQL Database is',
  'TXT_DB_TABLES': 'Database Tables',
  'TXT_DB_CON': 'connected',
  'TXT_DB_DES': 'disconnected',
  'TXT_ERR_HOST_EACCES': 'requires elevated privileges',
  'TXT_ERR_HOST_EADDRINUSE': 'is already in use',
}
